# Generated by Django 4.2.5 on 2023-09-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_myuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
